# Generated by Django 4.2.6 on 2023-10-23 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 23, 2, 38, 12, 444787, tzinfo=datetime.timezone.utc), verbose_name='作成日'),
        ),
    ]
